controller_manager:
  ros__parameters:
    update_rate: 25  # Hz

    pippo_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    pippo_diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

pippo_joint_state_broadcaster:
  ros__parameters:
    use_local_topic: true

pippo_diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["pippo_drivewhl_l_front_joint", "pippo_drivewhl_l_rear_joint"]
    right_wheel_names: ["pippo_drivewhl_r_front_joint", "pippo_drivewhl_r_rear_joint"]

    wheel_separation: 0.4
    wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.11

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    tf_frame_prefix_enable: false
    odom_frame_id: odom
    base_frame_id: pippo/base_link
    pose_covariance_diagonal : [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

    open_loop: true 
    enable_odom_tf: false

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    use_stamped_vel: false
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0

pluto/controller_manager:
  ros__parameters:
    update_rate: 25  # Hz

    pluto_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    pluto_diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

pluto/pluto_joint_state_broadcaster:
  ros__parameters:
    use_local_topic: true

pluto/pluto_diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["pluto_drivewhl_l_front_joint", "pluto_drivewhl_l_rear_joint"]
    right_wheel_names: ["pluto_drivewhl_r_front_joint", "pluto_drivewhl_r_rear_joint"]

    wheel_separation: 0.4
    wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.11

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    tf_frame_prefix_enable: true
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

    open_loop: true 
    enable_odom_tf: false

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    use_stamped_vel: false
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0
